laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('data-storage/{encryptedPath}', 'DataStorageController@index')->name('data-storage');

Route::middleware(['auth'])->group(function () {
    Route::view('/', 'dashboard')->name('dashboard');

    Route::prefix('product-categories')->name('product_categories.')->group(function () {
        Route::get('/', 'ProductCategoryController@index')->name('index');
        Route::get('/create', 'ProductCategoryController@create')->name('create');
        Route::post('/create', 'ProductCategoryController@store')->name('store');
        Route::get('/{id}', 'ProductCategoryController@edit')->name('edit');
        Route::post('/{id}', 'ProductCategoryController@update')->name('update');
        Route::delete('/{id}', 'ProductCategoryController@delete')->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');
        Route::get('/{id}', 'ProductController@edit')->name('edit');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::delete('/{id}', 'ProductController@delete')->name('delete');
    });

    Route::prefix('expenses')->name('expenses.')->group(function () {
        Route::get('/', 'ExpenseController@index')->name('index');
        Route::get('/create', 'ExpenseController@create')->name('create');
        Route::post('/', 'ExpenseController@store')->name('store');
        Route::delete('/{id}', 'ExpenseController@delete')->name('delete');
    });

    Route::prefix('cashier')->name('cashier.')->group(function () {
        Route::get('/', 'CashierController@index')->name('index');
        Route::get('/print/{encryptedCode}', 'CashierController@print')->name('print');
    });

    Route::prefix('transactions')->name('transactions.')->group(function () {
        Route::prefix('manage')->name('manage.')->group(function () {
            Route::get('/', 'TransactionController@manage')->name('index');
            Route::get('{id}', 'TransactionController@show')->name('show');

            Route::get('{id}/edit', 'TransactionController@edit')->name('edit');
            Route::put('{id}', 'TransactionController@update')->name('update');
            Route::get('{id}/item/add', 'TransactionItemController@add')->name('items.add');
            Route::post('{id}/item', 'TransactionItemController@store')->name('items.store');
            Route::delete('{transactionId}/item/{itemId}', 'TransactionItemController@delete')->name('items.delete');

            Route::delete('{id}', 'TransactionController@delete')->name('delete');
        });


        Route::get('/most-sales-products', 'TransactionController@mostSalesProducts')->name('most-sales-products');
        Route::get('/profit-and-loss', 'TransactionController@profitAndLoss')->name('profit-and-loss');
    });

    Route::get('reports', 'ReportController@index')->name('reports.index');
    Route::get('reports/{code}', 'ReportController@detail')->name('reports.detail');

    Route::prefix('settings')->name('settings.')->group(function () {
        Route::get('account', 'SettingController@account')->name('account');
        Route::post('account', 'SettingController@updateAccount')->name('account.update');
        Route::get('shop', 'SettingController@shop')->name('shop');
        Route::post('shop', 'SettingController@updateShop')->name('shop.update');
    });
});

laravel/app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TransactionDataTable;
use App\Models\Expense;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Transaction;
use App\Models\TransactionItem;
use Carbon\Carbon;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class TransactionController extends Controller
{
    /**
     * @return Factory|View
     */
    public function mostSalesProducts()
    {
        return view('transactions.most-sales-products', [
            'products' => Product::query()
                ->select('products.*', DB::raw('sum(transaction_items.qty) as sales'))
                ->join('transaction_items', 'products.id', '=', 'transaction_items.product_id')
                ->orderByDesc('sales')
                ->groupBy('products.id')
                ->get()
        ]);
    }

    /**
     * @return Factory|View
     */
    public function profitAndLoss(Request $request)
    {
        $startDate = $request->start_date ?? (new Carbon('first day of this month'))->format('Y-m-d');
        $endDate = $request->end_date ?? (new Carbon('last day of this month'))->format('Y-m-d');
        $category_id = $request->category_id;

        $transaction = Transaction::query()->whereHas('items');
        $expense = Expense::query();

        $transaction->whereDate('created_at', '>=', date('Y-m-d', strtotime($startDate)))
            ->whereDate('created_at', '<=', date('Y-m-d', strtotime($endDate)));
        $expense->whereDate('created_at', '>=', date('Y-m-d', strtotime($startDate)))
            ->whereDate('created_at', '<=', date('Y-m-d', strtotime($endDate)));

        if ($category_id) {
            $transaction->whereHas('items', function (Builder $item) use ($category_id) {
                $item->whereHas('product', function (Builder $product) use ($category_id) {
                    $product->where('category_id', $category_id);
                });
            });

            $expense->whereHas('product', function (Builder $product) use ($category_id) {
                $product->where('category_id', $category_id);
            });
        }

        return view('transactions.profit-and-loss', [
            'start_date' => $startDate,
            'end_date' => $endDate,
            'category_id' => $category_id,
            'categories' => ProductCategory::query()->orderBy('name')->pluck('name', 'id'),

            'totalTransaction' => $transaction->count(),
            'totalTransactionItem' => $transaction->with('items')->get()
                ->sum(function ($transactions) {
                    return $transactions->items->sum('qty');
                }),
            'profit' => $transaction->sum('total_price'),

            'totalExpense' => $expense->count(),
            'totalExpenseItem' => $expense->sum('qty'),
            'loss' => $expense->sum('total_price')
        ]);
    }

    /**
     * Show list transaction page
     *
     * @param Request $request
     * @param TransactionDataTable $dataTable
     * @return mixed
     */
    public function manage(Request $request, TransactionDataTable $dataTable)
    {
        $result = $dataTable
            ->setStartEndDate($request->start_date, $request->end_date);

        if ($request->print == 'print') {
            return view('transactions.print', [
                'dates' => [
                    $request->start_date,
                    $request->end_date
                ],
                'data' => $result->query(new Transaction())->get()
            ]);
        }

        return $result->render('transactions.manage');
    }

    /**
     * Show transaction detail page
     *
     * @param int $id
     * @return Factory|View
     */
    public function show($id)
    {
        $transaction = Transaction::query()->findOrFail($id);
        return view('transactions.show', [
            'transaction' => $transaction
        ]);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($id)
    {
        try {
            DB::beginTransaction();

            $transaction = Transaction::query()->find($id);
            if ($transaction) $transaction->delete();

            DB::commit();
            return redirect()->back()
                ->with($this->success(__('alert.success.delete')));
        } catch (\Exception $e) {
            DB::rollBack();
            report ($e);
            return redirect()->back()
                ->with($this->error(__('alert.error.delete')));
        }
    }

    /**
     * @param $id
     * @return Factory|View
     */
    public function edit($id)
    {
        return view('transactions.edit', [
            'products' => Product::query()->orderBy('name')->get(),
            'transaction' => Transaction::query()->findOrFail($id),
        ]);
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request)
    {
        $request->validate([
            'cash' => 'required'
        ]);

        try {
            $cash = (int) str_replace(',', '', $request->cash);

            DB::beginTransaction();

            $transaction = Transaction::query()->findOrFail($id);
            $transaction->cash = $cash;
            $transaction->change = $cash - $transaction->total_price;
            $transaction->save();

            DB::commit();
            return redirect()->route('transactions.manage.show', $id)
                ->with($this->success(__('alert.success.update')));
        } catch (\Exception $e) {
            DB::rollBack();
            report($e);
            return redirect()->back()
                ->with($this->error(__('alert.error.update')));
        }
    }
}

laravel/resources/views/transactions/edit.blade.php
@extends('layouts.app')
@section('title', 'Koreksi Transaksi')

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Koreksi Transaksi</h1>
        <p class="text-right">
            <a href="{{ route('transactions.manage.index') }}" class="btn btn-sm btn-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
        </p>
    </div>

    <div class="row mb-4">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('transactions.manage.update', $transaction->id) }}" method="post">@csrf @method('put')
                        <div class="form-group row">
                            <label class="col-md-3">Kode</label>
                            <div class="col-md-4">
                                <span>{{ $transaction->code }}</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Total Harga</label>
                            <div class="col-md-4">
                                <span>Rp. {{ number_format($transaction->total_price) }}</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cashInput" class="col-md-3">Bayar</label>
                            <div class="col-md-4">
                                <input id="cashInput"
                                       type="text"
                                       class="form-control currency-mask"
                                       min="1"
                                       name="cash"
                                       value="{{ $transaction->cash }}"
                                >
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Kembali</label>
                            <div class="col-md-4">
                                <span>Rp. {{ number_format($transaction->change) }}</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3"></div>
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-primary">Koreksi Transaksi</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="text-right mb-4">
                        <a href="{{ route('transactions.manage.items.add', $transaction->id) }}" role="button" class="btn btn-sm btn-primary">Tambah Item</a>
                    </div>
                    <table class="table small">
                        <thead>
                            <tr>
                                <td>Kategori</td>
                                <td>Produk</td>
                                <td>Total Harga</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($transaction->items as $item)
                                <tr>
                                    <td>{{ $item->product->category->name ?? '-' }}</td>
                                    <td>
                                        <p class="mb-0">{{ $item->product->name }}</p>
                                        <p class="mb-0">
                                            <span>{{ $item->qty }} x Rp. {{ number_format($item->product->price) }}</span>
                                        </p>
                                    <td>Rp. {{ number_format($item->total_price) }}</td>
                                    <td>
                                        <form action="{{ route('transactions.manage.items.delete', [$transaction->id, $item->id]) }}" method="post">
                                            @csrf @method('delete')
                                            <button type="submit" class="btn btn-link btn-sm text-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/transactions/manage.blade.php
@extends('layouts.app')
@section('title', 'Kelola Penjualan')

@push('styles')
    <link href="{{ asset('sb-admin-2/vendor/datatables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar Penjualan</h1>
    </div>

    <div class="row mb-4">
        <div class="col">
            <div class="card">
                <div class="card-body pb-0">
                    <form action="" method="get">
                        <div class="form-group row">
                            <div class="col-md-4 mb-2">
                                <label class="mb-0">Periode</label>
                                <input type="date" name="start_date" class="form-control form-control-sm" value="{{ request('start_date') }}">
                            </div>
                            <div class="col-md-4 mb-2">
                                <label class="mb-0">Sampai</label>
                                <input type="date" name="end_date" class="form-control form-control-sm" value="{{ request('end_date') }}">
                            </div>
                            <div class="col-md-4 mb-2 mt-auto">
                                <button type="submit" class="btn btn-sm btn-primary">Cari Data Transaksi</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                   {{ $dataTable->table() }}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <!-- Page level plugins -->
    <script src="{{ asset('sb-admin-2/vendor/datatables/datatables.min.js') }}"></script>

    {{ $dataTable->scripts() }}

    <script>
        function printPage() {
            let url = document.location.href;
            if(document.location.href.toString().includes('?')) {
                url = document.location.href+"&print=print";
            }else{
                url = document.location.href+"?print=print";
            }

            window.open(url, '_blank');
        }
    </script>
@endpush

laravel/resources/views/transactions/most-sales-products.blade.php
@extends('layouts.app')
@section('title', 'Barang Terlaku')

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar Produk Terlaku</h1>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <td>No</td>
                            <td>Gambar</td>
                            <td>Nama Produk</td>
                            <td>Terjual</td>
                        </tr>
                        </thead>
                        <tbody>
                        @php $counter = 1; @endphp
                        @foreach ($products as $product)
                            <tr>
                                <td>{{ $counter++ }}</td>
                                <td>
                                    <img class="img-crop rounded shadow-sm" width="150" src="{{ $product->image }}" alt="{{ $product->image }}">
                                </td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->sales }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/transactions/print.blade.php
<!doctype html>
<html lang="id">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
				content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Laporan</title>

	<link rel="stylesheet" href="{{ asset('css/tailwind.min.css') }}">

	<style>
		@page {
			size: A4;
			margin: 20mm;
		}
		/* print styles */
		@media print {
			body {
				visibility: hidden;
				margin: 0;
				padding: 0;
				color: #000;
				background-color: #fff;
			}
			.page {
				visibility: visible;
				box-shadow: none;
				margin: 0;
				padding: 0;
			}
		}

		@media screen {
			.page {
				width: 210mm;
				min-height: 297mm;
				padding: 20mm
			}
		}
	</style>
</head>
<body class="bg-gray-600">
<div class="page bg-white mx-auto mt-12 shadow-2xl">

	<div class="text-center mb-6 pb-1 border-b-2 border-black">
		<h1 class="text-2xl font-bold">{{ Shop::get()->name ?? 'Nama Toko' }}</h1>
		<p class="pb-3 border-b-4 border-black">{{ Shop::get()->address ?? 'Jl. Alamat Lengkap Toko' }}</p>
	</div>

	<div class="text-center mb-10 font-bold">
		<h1 class="text-center text-xl">Laporan Penjualan</h1>
		@if($dates[0] || $dates[1])
			<p class="text-sm">Periode {{ date('d M Y', strtotime($dates[0])) }} s/d {{ date('d M Y', strtotime($dates[1])) }}</p>
		@endif
	</div>

	<table class="table-auto w-full text-xs mb-8">
		@foreach($data as $key => $datum)

			<tr class="text-left">
				<th class="border border-black px-2 py-1">#</th>
				<th colspan="2" class="border border-black px-2 py-1">Kode</th>
				<th colspan="2" class="border border-black px-2 py-1">Tanggal</th>
				<th class="border border-black px-2 py-1">Total Harga</th>
				<th class="border border-black px-2 py-1">Total Laba</th>
			</tr>
			<tr>
				<td class="border border-black px-2 py-1">{{ $key+1 }}</td>
				<td colspan="2" class="border border-black px-2 py-1">{{ $datum->code }}</td>
				<td colspan="2" class="border border-black px-2 py-1">{{ $datum->created_at->format('d-m-Y H:i') }} {{ config('kasir.timezone') }}</td>
				<td class="border border-black px-2 py-1 text-right">Rp. {{ number_format($datum->total_price) }},-</td>
				<td class="border border-black px-2 py-1 text-right">Rp. {{ number_format($datum->getTotalProfit()) }},-</td>
			</tr>

			<tr><td colspan="7" class="py-1"></td></tr>

			<tr class="text-left">
				<th class="border border-black px-2 py-1">#</th>
				<th class="border border-black px-2 py-1">Produk</th>
				<th class="border border-black px-2 py-1">Qty</th>
				<th class="border border-black px-2 py-1">Harga Beli</th>
				<th class="border border-black px-2 py-1">Harga Jual</th>
				<th class="border border-black px-2 py-1">Sub Total</th>
				<th class="border border-black px-2 py-1">Laba</th>
			</tr>
			@foreach ($datum->items as $keyItem => $item)
				<tr>
					<td class="border border-black px-2 py-1">{{ $keyItem+1 }}</td>
					<td class="border border-black px-2 py-1">{{ $item->product->name ?? '-' }}</td>
					<td class="border border-black px-2 py-1">{{ $item->qty }}</td>
					<td class="border border-black px-2 py-1 text-right">Rp. {{ number_format($item->product->price ?? '-') }},-</td>
					<td class="border border-black px-2 py-1 text-right">Rp. {{ number_format($item->product->getAverageBuyPrice() ?? '-') }},-</td>
					<td class="border border-black px-2 py-1 text-right">Rp. {{ number_format($item->total_price ?? '-') }},-</td>
					<td class="border border-black px-2 py-1 text-right">Rp. {{ number_format($item->getProfit()) }},-</td>
				</tr>
			@endforeach

			<tr><td colspan="7" class="py-4"></td></tr>

		@endforeach
	</table>

</div>
<button class="py-3 px-4 bg-blue-400 hover:bg-blue-300 text-white uppercase font-bold rounded-lg shadow-2xl fixed bottom-0 right-0 mb-10 mr-10" onclick="printPage();">Print</button>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    jQuery(document).ready(function($){
        nsZoomZoom();
        $( window ).resize(function() {
            console.log($(window).width());
            nsZoomZoom();
        });

        function nsZoomZoom() {
            htmlWidth = $(window).width();
            pageWidth = $('.page').width();

            if ((htmlWidth * 0.8) > pageWidth)
                scale = 1
            else {
                scale = (htmlWidth / pageWidth) * 0.8;
            }

            // Req for IE9
            $(".page").css('transform-origin', 'top left');
            $(".page").css('-ms-transform', 'scale(' + scale + ')');
            $(".page").css('transform', 'scale(' + scale + ')');
        }
    });

    function printPage() {
        $( window ).resize(function(e) {
            return false;
        });

        $(".page").css('transform-origin', 'top left');
        $(".page").css('-ms-transform', 'scale(1)');
        $(".page").css('transform', 'scale(1)');

        setTimeout(window.print(), 1000)
    }
</script>
</body>
</html>

laravel/resources/views/transactions/profit-and-loss.blade.php
@extends('layouts.app')
@section('title', 'Rugi Laba')

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Rekapitulasi Laporan Rugi Laba</h1>
    </div>

    <div class="row mb-4">
        <div class="col">
            <div class="card">
                <div class="card-body pb-0">
                    <form action="" method="get">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Periode</label>
                                    <input type="date" name="start_date" class="form-control form-control-sm" value="{{ $start_date }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Sampai</label>
                                    <input type="date" name="end_date" class="form-control form-control-sm" value="{{ $end_date }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="categoryIdInput">Kategori Produk</label>
                            <select name="category_id" id="categoryIdInput" class="form-control">
                                <option value="">Semua Kategori</option>
                                @foreach($categories as $id => $name)
                                    <option value="{{ $id }}" {{ $category_id == $id ? 'selected' : '' }}>{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-sm btn-primary">Terapkan Filter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-5">
                        <div class="col-md-6">
                            <h5 class="mb-3">Pendapatan</h5>
                            <table class="w-100">
                                <tr><td>Jumlah Transaksi</td><td>:</td><td>{{ $totalTransaction ?? 0 }} Transaksi</td></tr>
                                <tr><td>Jumlah Item Terjual</td><td>:</td><td>{{ $totalTransactionItem ?? 0 }} Item</td></tr>
                                <tr><td>Total</td><td>:</td><td>Rp. {{ number_format($profit) }}</td></tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h5 class="mb-3">Pengeluaran</h5>
                            <table class="w-100">
                                <tr><td>Jumlah Pengeluaran</td><td>:</td><td>{{ $totalExpense ?? 0 }} Transaksi</td></tr>
                                <tr><td>Jumlah Item Dibeli</td><td>:</td><td>{{ $totalExpenseItem ?? 0 }} Item</td></tr>
                                <tr><td>Total</td><td>:</td><td>Rp. {{ number_format($loss) }}</td></tr>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <table class="w-100">
                                <tr><td class="h4">Grand Total</td><td class="h4 text-right">Rp. {{ number_format($profit - $loss) }}</td></tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/transactions/show.blade.php
@extends('layouts.app')
@section('title', 'Detail Transaksi')

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Detail Transaksi</h1>
        <p class="text-right">
            <a href="{{ route('transactions.manage.index') }}" class="btn btn-sm btn-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
            <a href="{{ route('cashier.print', encrypt($transaction->code)) }}" target="_blank" class="btn btn-sm btn-dark"><i class="fa fa-print"></i></a>
        </p>
    </div>

    <div class="row">
        <div class="col-md-7 mb-4 mb-md-0">
            <div class="card">
                <div class="card-header">
                    <h6 class="card-title mb-0">{{ $transaction->items->count() }} Item</h6>
                </div>
                <table class="table small">
                    @foreach($transaction->items as $item)
                        <tr>
                            <td style="width: 100px;">
                                <img src="{{ $item->product->image }}" alt="{{ $item->product->name }}" width="100" class="img-crop rounded shadow-sm">
                            </td>
                            <td>
                                <p class="mb-0">{{ $item->product->name }}</p>
                                <p>{{ $item->qty }} x Rp. {{ number_format($item->product->price) }}</p>
                                <h5>Rp. {{ number_format($item->total_price) }}</h5>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <table class="table table-borderless mb-0 small">
                    <tr class="bg-light"><td colspan="3" class="border-bottom"><span class="h6 card-title mb-0">Detail Transaksi</span></td></tr>
                    <tr><td>Kode</td><td>:</td><td>{{ $transaction->code }}</td></tr>
                    <tr><td>Tanggal</td><td>:</td><td>{{ date('d-m-Y', strtotime($transaction->created_at)) }}</td></tr>
                    <tr><td>Waktu</td><td>:</td><td>{{ date('H:m', strtotime($transaction->created_at)) }} {{ config('kasir.timezone') }}</td></tr>
                    <tr class="bg-light"><td colspan="3" class="border-bottom border-top"><span class="h6 card-title mb-0">Detail Pembayaran</span></td></tr>
                    <tr><td>Total Transaksi</td><td>:</td><td>Rp. {{ number_format($transaction->total_price) }}</td></tr>
                    <tr><td>Bayar</td><td>:</td><td>Rp. {{ number_format($transaction->cash) }}</td></tr>
                    <tr><td>Kembali</td><td>:</td><td>Rp. {{ number_format($transaction->change) }}</td></tr>
                </table>
            </div>
        </div>
    </div>
@endsection