laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('data-storage/{encryptedPath}', 'DataStorageController@index')->name('data-storage');

Route::middleware(['auth'])->group(function () {
    Route::view('/', 'dashboard')->name('dashboard');

    Route::prefix('product-categories')->name('product_categories.')->group(function () {
        Route::get('/', 'ProductCategoryController@index')->name('index');
        Route::get('/create', 'ProductCategoryController@create')->name('create');
        Route::post('/create', 'ProductCategoryController@store')->name('store');
        Route::get('/{id}', 'ProductCategoryController@edit')->name('edit');
        Route::post('/{id}', 'ProductCategoryController@update')->name('update');
        Route::delete('/{id}', 'ProductCategoryController@delete')->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');
        Route::get('/{id}', 'ProductController@edit')->name('edit');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::delete('/{id}', 'ProductController@delete')->name('delete');
    });

    Route::prefix('expenses')->name('expenses.')->group(function () {
        Route::get('/', 'ExpenseController@index')->name('index');
        Route::get('/create', 'ExpenseController@create')->name('create');
        Route::post('/', 'ExpenseController@store')->name('store');
        Route::delete('/{id}', 'ExpenseController@delete')->name('delete');
    });

    Route::prefix('cashier')->name('cashier.')->group(function () {
        Route::get('/', 'CashierController@index')->name('index');
        Route::get('/print/{encryptedCode}', 'CashierController@print')->name('print');
    });

    Route::prefix('transactions')->name('transactions.')->group(function () {
        Route::prefix('manage')->name('manage.')->group(function () {
            Route::get('/', 'TransactionController@manage')->name('index');
            Route::get('{id}', 'TransactionController@show')->name('show');

            Route::get('{id}/edit', 'TransactionController@edit')->name('edit');
            Route::put('{id}', 'TransactionController@update')->name('update');
            Route::get('{id}/item/add', 'TransactionItemController@add')->name('items.add');
            Route::post('{id}/item', 'TransactionItemController@store')->name('items.store');
            Route::delete('{transactionId}/item/{itemId}', 'TransactionItemController@delete')->name('items.delete');

            Route::delete('{id}', 'TransactionController@delete')->name('delete');
        });


        Route::get('/most-sales-products', 'TransactionController@mostSalesProducts')->name('most-sales-products');
        Route::get('/profit-and-loss', 'TransactionController@profitAndLoss')->name('profit-and-loss');
    });

    Route::get('reports', 'ReportController@index')->name('reports.index');
    Route::get('reports/{code}', 'ReportController@detail')->name('reports.detail');

    Route::prefix('settings')->name('settings.')->group(function () {
        Route::get('account', 'SettingController@account')->name('account');
        Route::post('account', 'SettingController@updateAccount')->name('account.update');
        Route::get('shop', 'SettingController@shop')->name('shop');
        Route::post('shop', 'SettingController@updateShop')->name('shop.update');
    });
});

laravel/app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TransactionDataTable;
use App\Models\Expense;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Transaction;
use App\Models\TransactionItem;
use Carbon\Carbon;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class TransactionController extends Controller
{
    /**
     * @return Factory|View
     */
    public function mostSalesProducts()
    {
        return view('transactions.most-sales-products', [
            'products' => Product::query()
                ->select('products.*', DB::raw('sum(transaction_items.qty) as sales'))
                ->join('transaction_items', 'products.id', '=', 'transaction_items.product_id')
                ->orderByDesc('sales')
                ->groupBy('products.id')
                ->get()
        ]);
    }

    /**
     * @return Factory|View
     */
    public function profitAndLoss(Request $request)
    {
        $startDate = $request->start_date ?? (new Carbon('first day of this month'))->format('Y-m-d');
        $endDate = $request->end_date ?? (new Carbon('last day of this month'))->format('Y-m-d');
        $category_id = $request->category_id;

        $transaction = Transaction::query()->whereHas('items');
        $expense = Expense::query();

        $transaction->whereDate('created_at', '>=', date('Y-m-d', strtotime($startDate)))
            ->whereDate('created_at', '<=', date('Y-m-d', strtotime($endDate)));
        $expense->whereDate('created_at', '>=', date('Y-m-d', strtotime($startDate)))
            ->whereDate('created_at', '<=', date('Y-m-d', strtotime($endDate)));

        if ($category_id) {
            $transaction->whereHas('items', function (Builder $item) use ($category_id) {
                $item->whereHas('product', function (Builder $product) use ($category_id) {
                    $product->where('category_id', $category_id);
                });
            });

            $expense->whereHas('product', function (Builder $product) use ($category_id) {
                $product->where('category_id', $category_id);
            });
        }

        return view('transactions.profit-and-loss', [
            'start_date' => $startDate,
            'end_date' => $endDate,
            'category_id' => $category_id,
            'categories' => ProductCategory::query()->orderBy('name')->pluck('name', 'id'),

            'totalTransaction' => $transaction->count(),
            'totalTransactionItem' => $transaction->with('items')->get()
                ->sum(function ($transactions) {
                    return $transactions->items->sum('qty');
                }),
            'profit' => $transaction->sum('total_price'),

            'totalExpense' => $expense->count(),
            'totalExpenseItem' => $expense->sum('qty'),
            'loss' => $expense->sum('total_price')
        ]);
    }

    /**
     * Show list transaction page
     *
     * @param Request $request
     * @param TransactionDataTable $dataTable
     * @return mixed
     */
    public function manage(Request $request, TransactionDataTable $dataTable)
    {
        $result = $dataTable
            ->setStartEndDate($request->start_date, $request->end_date);

        if ($request->print == 'print') {
            return view('transactions.print', [
                'dates' => [
                    $request->start_date,
                    $request->end_date
                ],
                'data' => $result->query(new Transaction())->get()
            ]);
        }

        return $result->render('transactions.manage');
    }

    /**
     * Show transaction detail page
     *
     * @param int $id
     * @return Factory|View
     */
    public function show($id)
    {
        $transaction = Transaction::query()->findOrFail($id);
        return view('transactions.show', [
            'transaction' => $transaction
        ]);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($id)
    {
        try {
            DB::beginTransaction();

            $transaction = Transaction::query()->find($id);
            if ($transaction) $transaction->delete();

            DB::commit();
            return redirect()->back()
                ->with($this->success(__('alert.success.delete')));
        } catch (\Exception $e) {
            DB::rollBack();
            report ($e);
            return redirect()->back()
                ->with($this->error(__('alert.error.delete')));
        }
    }

    /**
     * @param $id
     * @return Factory|View
     */
    public function edit($id)
    {
        return view('transactions.edit', [
            'products' => Product::query()->orderBy('name')->get(),
            'transaction' => Transaction::query()->findOrFail($id),
        ]);
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request)
    {
        $request->validate([
            'cash' => 'required'
        ]);

        try {
            $cash = (int) str_replace(',', '', $request->cash);

            DB::beginTransaction();

            $transaction = Transaction::query()->findOrFail($id);
            $transaction->cash = $cash;
            $transaction->change = $cash - $transaction->total_price;
            $transaction->save();

            DB::commit();
            return redirect()->route('transactions.manage.show', $id)
                ->with($this->success(__('alert.success.update')));
        } catch (\Exception $e) {
            DB::rollBack();
            report($e);
            return redirect()->back()
                ->with($this->error(__('alert.error.update')));
        }
    }
}

laravel/resources/views/transactions/items/add.blade.php
@extends('layouts.app')
@section('title', 'Tambah Item')

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Tambah Item</h1>
        <p class="text-right">
            <a href="{{ route('transactions.manage.edit', $transaction->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
        </p>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('transactions.manage.items.store', $transaction->id) }}" method="post">
                        @csrf
                        <div class="form-group row">
                            <label class="col-md-3">Kode Transaksi</label>
                            <div class="col-md-9">
                                <p>{{ $transaction->code }}</p>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="product_id" class="col-form-label col-md-3">Product</label>
                            <div class="col-md-9">
                                <select name="product_id" id="product_id" class="form-control">
                                    <option value="">-- Pilih Produk --</option>
                                    @foreach($products as $product)
                                        <option value="{{ $product->id }}">
                                            <span>[{{ $product->category->name ?? 'Tanpa Kategori' }}]</span>
                                            <span>{{ $product->name }}</span>
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="qty" class="col-form-label col-md-3">Jumlah</label>
                            <div class="col-md-3">
                                <input type="number" id="qty" name="qty" value="1" min="1" class="form-control" autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3"></div>
                            <div class="col-md-9">
                                <button type="submit" class="btn btn-primary">Tambah Item</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection