laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('data-storage/{encryptedPath}', 'DataStorageController@index')->name('data-storage');

Route::middleware(['auth'])->group(function () {
    Route::view('/', 'dashboard')->name('dashboard');

    Route::prefix('product-categories')->name('product_categories.')->group(function () {
        Route::get('/', 'ProductCategoryController@index')->name('index');
        Route::get('/create', 'ProductCategoryController@create')->name('create');
        Route::post('/create', 'ProductCategoryController@store')->name('store');
        Route::get('/{id}', 'ProductCategoryController@edit')->name('edit');
        Route::post('/{id}', 'ProductCategoryController@update')->name('update');
        Route::delete('/{id}', 'ProductCategoryController@delete')->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');
        Route::get('/{id}', 'ProductController@edit')->name('edit');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::delete('/{id}', 'ProductController@delete')->name('delete');
    });

    Route::prefix('expenses')->name('expenses.')->group(function () {
        Route::get('/', 'ExpenseController@index')->name('index');
        Route::get('/create', 'ExpenseController@create')->name('create');
        Route::post('/', 'ExpenseController@store')->name('store');
        Route::delete('/{id}', 'ExpenseController@delete')->name('delete');
    });

    Route::prefix('cashier')->name('cashier.')->group(function () {
        Route::get('/', 'CashierController@index')->name('index');
        Route::get('/print/{encryptedCode}', 'CashierController@print')->name('print');
    });

    Route::prefix('transactions')->name('transactions.')->group(function () {
        Route::prefix('manage')->name('manage.')->group(function () {
            Route::get('/', 'TransactionController@manage')->name('index');
            Route::get('{id}', 'TransactionController@show')->name('show');

            Route::get('{id}/edit', 'TransactionController@edit')->name('edit');
            Route::put('{id}', 'TransactionController@update')->name('update');
            Route::get('{id}/item/add', 'TransactionItemController@add')->name('items.add');
            Route::post('{id}/item', 'TransactionItemController@store')->name('items.store');
            Route::delete('{transactionId}/item/{itemId}', 'TransactionItemController@delete')->name('items.delete');

            Route::delete('{id}', 'TransactionController@delete')->name('delete');
        });


        Route::get('/most-sales-products', 'TransactionController@mostSalesProducts')->name('most-sales-products');
        Route::get('/profit-and-loss', 'TransactionController@profitAndLoss')->name('profit-and-loss');
    });

    Route::get('reports', 'ReportController@index')->name('reports.index');
    Route::get('reports/{code}', 'ReportController@detail')->name('reports.detail');

    Route::prefix('settings')->name('settings.')->group(function () {
        Route::get('account', 'SettingController@account')->name('account');
        Route::post('account', 'SettingController@updateAccount')->name('account.update');
        Route::get('shop', 'SettingController@shop')->name('shop');
        Route::post('shop', 'SettingController@updateShop')->name('shop.update');
    });
});

laravel/resources/views/layouts/actions.blade.php
<div class="text-nowrap">
    @if (isset($show)) <a href="{{ $show }}" class="text-info border rounded border-info px-2"><i class="fa fa-eye"></i></a> @endif
    @if (isset($print)) <a href="{{ $print }}" target="_blank" class="text-success border rounded border-success px-2"><i class="fa fa-print"></i></a> @endif
    @if (isset($edit)) <a href="{{ $edit }}" class="text-warning border rounded border-warning px-2"><i class="fa fa-edit"></i></a> @endif
    @if (isset($delete)) 
    <a role="button" class="text-danger border rounded border-danger px-2" onclick="$('#delete-{{ $id }}').submit();"><i class="fa fa-trash"></i></a>
    <form id="delete-{{ $id }}" action="{{ $delete }}" method="post" hidden>@csrf @method('delete')</form>
    @endif
</div>

laravel/resources/views/layouts/alert.blade.php
@if (session('alert'))
    <div class="row">
        <div class="col">
            <div class="alert alert-{{ session('alert')['class'] }} alert-dismissible fade show" role="alert">
                {{ session('alert')['message'] }}

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
@endif

@if ($errors->any())
    <div class="row">
        <div class="col">
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ $error }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
        </div>
    </div>
@endif

laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
        @hasSection('title')
            @yield('title') - {{ config('app.name') }}
        @else
            {{ config('app.name') }}
        @endif
    </title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('sb-admin-2/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('sb-admin-2/css/sb-admin-2.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    @stack('styles')

</head>

<body id="page-top" class="sidebar-toggled">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    @include('layouts.sidebar')
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            @include('layouts.topbar')
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                @include('layouts.alert')

                @yield('contents')
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        @include('layouts.footer')
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Bootstrap core JavaScript-->
<script src="{{ asset('sb-admin-2/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('sb-admin-2/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('sb-admin-2/js/sb-admin-2.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>

<script src="https://unpkg.com/imask"></script>
<script>
    var currencyMask = IMask(
        document.querySelector('.currency-mask'),
        {
            mask: 'num',
            blocks: {
                num: {
                    // nested masks are available!
                    mask: Number,
                    thousandsSeparator: ','
                }
            }
        }
    );
</script>
@stack('scripts')

</body>

</html>

laravel/resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{ config('app.name') }} - @yield('title')</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('sb-admin-2/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('sb-admin-2/css/sb-admin-2.min.css') }}" rel="stylesheet">

</head>

<body class="bg-gradient-dark">

@yield('contents')

<!-- Bootstrap core JavaScript-->
<script src="{{ asset('sb-admin-2/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('sb-admin-2/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('sb-admin-2/js/sb-admin-2.min.js') }}"></script>

</body>

</html>

laravel/resources/views/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; {{ config('app.name') }} 2020</span>
        </div>
    </div>
</footer>

laravel/resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon">
            <img src="{{ \App\Models\Shop::get()->photo ?? '' }}" class="img-crop circle" width="50" height="50" alt="">
        </div>
        <div class="sidebar-brand-text mx-3">{{ config('app.name') }}</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'dashboard') > -1) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'cashier') > -1) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('cashier.index') }}">
            <i class="fas fa-fw fa-calculator"></i>
            <span>Kasir</span>
        </a>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'product_categories') > -1) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('product_categories.index') }}">
            <i class="fas fa-boxes"></i>
            <span>Kelola Kategori Produk</span>
        </a>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'products') > -1) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('products.index') }}">
            <i class="fas fa-box-open"></i>
            <span>Kelola Produk</span>
        </a>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'expenses') > -1) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('expenses.index') }}">
            <i class="fas fa-money-bill"></i>
            <span>Kelola Pengeluaran</span>
        </a>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'transactions') > -1) ? 'active' : '' }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#transactionMenu" aria-expanded="false" aria-controls="transactionMenu">
            <i class="fas fa-fw fa-shopping-cart"></i>
            <span>Kelola Penjualan</span>
        </a>
        <div id="transactionMenu" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar" style="">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('transactions.most-sales-products') }}">Barang Terlaku</a>
                <a class="collapse-item" href="{{ route('transactions.manage.index') }}">Transaksi Penjualan</a>
                <a class="collapse-item" href="{{ route('transactions.profit-and-loss') }}">Rugi Laba</a>
            </div>
        </div>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'reports') > -1) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('reports.index') }}">
            <i class="fas fa-fw fa-book"></i>
            <span>Laporan</span>
        </a>
    </li>

    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'settings') > -1) ? 'active' : '' }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#settingsMenu" aria-expanded="false" aria-controls="settingsMenu">
            <i class="fas fa-fw fa-cog"></i>
            <span>Pengaturan</span>
        </a>
        <div id="settingsMenu" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar" style="">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('settings.account') }}">Akun</a>
                <a class="collapse-item" href="{{ route('settings.shop') }}">Toko</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

laravel/resources/views/layouts/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow-sm">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle">
        <i class="fa fa-bars"></i>
    </button>

    <h5 class="mb-0 d-none d-md-block">{{ \App\Models\Shop::get()->name ?? '' }}</h5>
    @if (Shop::get())
    <img class="d-block d-md-none img-crop circle" width="40" height="40" src="{{ Shop::get()->photo }}" alt="">
    @endif

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown no-arrow">
            <a class="nav-link" href="#">
                <img src="{{ auth()->user()->avatar }}" alt="" class="d-none d-md-block img-crop circle mr-3" width="40" height="40">
                <span class="text-gray-600 small">Welcome, {{ auth()->user()->name }}</span>
            </a>
        </li>

        <li class="nav-item dropdown no-arrow">
            <a class="nav-link" href="#" onclick="$('#logoutForm').submit()">
                <i class="fa fa-sign-out-alt"></i>
                <span class="ml-2 text-gray-600 small">Logout</span>
            </a>
            <form id="logoutForm" action="{{ route('logout') }}" method="post" hidden>@csrf</form>
        </li>

    </ul>

</nav>