laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('data-storage/{encryptedPath}', 'DataStorageController@index')->name('data-storage');

Route::middleware(['auth'])->group(function () {
    Route::view('/', 'dashboard')->name('dashboard');

    Route::prefix('product-categories')->name('product_categories.')->group(function () {
        Route::get('/', 'ProductCategoryController@index')->name('index');
        Route::get('/create', 'ProductCategoryController@create')->name('create');
        Route::post('/create', 'ProductCategoryController@store')->name('store');
        Route::get('/{id}', 'ProductCategoryController@edit')->name('edit');
        Route::post('/{id}', 'ProductCategoryController@update')->name('update');
        Route::delete('/{id}', 'ProductCategoryController@delete')->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');
        Route::get('/{id}', 'ProductController@edit')->name('edit');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::delete('/{id}', 'ProductController@delete')->name('delete');
    });

    Route::prefix('expenses')->name('expenses.')->group(function () {
        Route::get('/', 'ExpenseController@index')->name('index');
        Route::get('/create', 'ExpenseController@create')->name('create');
        Route::post('/', 'ExpenseController@store')->name('store');
        Route::delete('/{id}', 'ExpenseController@delete')->name('delete');
    });

    Route::prefix('cashier')->name('cashier.')->group(function () {
        Route::get('/', 'CashierController@index')->name('index');
        Route::get('/print/{encryptedCode}', 'CashierController@print')->name('print');
    });

    Route::prefix('transactions')->name('transactions.')->group(function () {
        Route::prefix('manage')->name('manage.')->group(function () {
            Route::get('/', 'TransactionController@manage')->name('index');
            Route::get('{id}', 'TransactionController@show')->name('show');

            Route::get('{id}/edit', 'TransactionController@edit')->name('edit');
            Route::put('{id}', 'TransactionController@update')->name('update');
            Route::get('{id}/item/add', 'TransactionItemController@add')->name('items.add');
            Route::post('{id}/item', 'TransactionItemController@store')->name('items.store');
            Route::delete('{transactionId}/item/{itemId}', 'TransactionItemController@delete')->name('items.delete');

            Route::delete('{id}', 'TransactionController@delete')->name('delete');
        });


        Route::get('/most-sales-products', 'TransactionController@mostSalesProducts')->name('most-sales-products');
        Route::get('/profit-and-loss', 'TransactionController@profitAndLoss')->name('profit-and-loss');
    });

    Route::get('reports', 'ReportController@index')->name('reports.index');
    Route::get('reports/{code}', 'ReportController@detail')->name('reports.detail');

    Route::prefix('settings')->name('settings.')->group(function () {
        Route::get('account', 'SettingController@account')->name('account');
        Route::post('account', 'SettingController@updateAccount')->name('account.update');
        Route::get('shop', 'SettingController@shop')->name('shop');
        Route::post('shop', 'SettingController@updateShop')->name('shop.update');
    });
});

laravel/resources/views/expenses/create.blade.php
@extends('layouts.app')
@section('title', 'Tambah Data Pengeluaran')

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Data Pengeluaran</h1>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('expenses.store') }}" method="post">
                        @csrf
                        <div class="form-group row">
                            <label for="product_id" class="col-md-3 col-form-label">Produk</label>
                            <div class="col-md-9">
                                <select name="product_id" id="product_id" class="form-control">
                                    <option value="">-- Pilih Produk --</option>
                                    @foreach($products as $product)
                                        <option value="{{ $product->id }}" {{ old('product_id') == $product->id ? 'selected' : '' }}>[{{ $product->category->name ?? '-' }}] {{ $product->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="qty" class="col-md-3 col-form-label">Jumlah</label>
                            <div class="col-md-4">
                                <input type="number" min="1" name="qty" id="qty" class="form-control" value="{{ old('qty') }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="price" class="col-md-3 col-form-label">Harga Satuan</label>
                            <div class="col-md-4">
                                <input type="text" min="0" name="price" id="price" class="form-control currency-mask" value="{{ old('price') }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3"></div>
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-primary">Tambah</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/expenses/index.blade.php
@extends('layouts.app')
@section('title', 'Pengeluaran')

@push('styles')
    <link href="{{ asset('sb-admin-2/vendor/datatables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('contents')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar Pengeluaran</h1>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    {{ $dataTable->table() }}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <!-- Page level plugins -->
    <script src="{{ asset('sb-admin-2/vendor/datatables/datatables.min.js') }}"></script>

    {{ $dataTable->scripts() }}
@endpush